version: "3.8"

services:
  vite-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node-ts-app
    networks:
      - app-network

  node-ts-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=http://localhost:8080
      - DB_URI=mongodb://mongodb:27017/marvel
      - BASE_URL=https://api.themoviedb.org/3
      - API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MjdhMDcxMzk3OThjZGQ1NjA0ZTQyOTcwNzdjMzQzNSIsIm5iZiI6MTczMTMyOTMzOS44NDMyNDMxLCJzdWIiOiI2NzMxZmMwZjBkNzU4MDQwZWI0YjE2MmIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.e-7ALW2PRpz76PqLzoKP-bsOBeMchAtLx7TW1QOH-so
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
